[Resolve]
# The resolver ABI for applications is the local DNS stub.  This is used by
# both glibc's "dns" NSS backend and musl's native resolver.
DNSStubListener=yes
DNS=
FallbackDNS=
DNSSEC=allow-downgrade
DNSOverTLS=no
Cache=yes
ReadEtcHosts=yes
