# Distributed under the terms of the GNU General Public License v2
# lockstep-cargo-managed: true
# lockstep-cargo-deps: begin
CARGO_DEPS="
	rust-crates/ahash-0.8.12
	rust-crates/aho-corasick-1.1.4
	rust-crates/anstream-0.6.21
	rust-crates/anstyle-1.0.13
	rust-crates/anstyle-parse-0.2.7
	rust-crates/anstyle-query-1.1.5
	rust-crates/anstyle-wincon-3.0.11
	rust-crates/autocfg-1.5.0
	rust-crates/base64-0.13.1
	rust-crates/bitflags-2.10.0
	rust-crates/bumpalo-3.19.0
	rust-crates/castaway-0.2.4
	rust-crates/cc-1.2.48
	rust-crates/cfg-if-1.0.4
	rust-crates/colorchoice-1.0.4
	rust-crates/compact_str-0.9.0
	rust-crates/console-0.16.1
	rust-crates/crossbeam-deque-0.8.6
	rust-crates/crossbeam-epoch-0.9.18
	rust-crates/crossbeam-utils-0.8.21
	rust-crates/darling-0.20.11
	rust-crates/darling_core-0.20.11
	rust-crates/darling_macro-0.20.11
	rust-crates/dary_heap-0.3.8
	rust-crates/derive_builder-0.20.2
	rust-crates/derive_builder_core-0.20.2
	rust-crates/derive_builder_macro-0.20.2
	rust-crates/either-1.15.0
	rust-crates/encode_unicode-1.0.0
	rust-crates/env_filter-0.1.4
	rust-crates/env_logger-0.11.8
	rust-crates/errno-0.3.14
	rust-crates/esaxx-rs-0.1.10
	rust-crates/fastrand-2.3.0
	rust-crates/find-msvc-tools-0.1.5
	rust-crates/fnv-1.0.7
	rust-crates/futures-0.3.31
	rust-crates/futures-channel-0.3.31
	rust-crates/futures-core-0.3.31
	rust-crates/futures-executor-0.3.31
	rust-crates/futures-io-0.3.31
	rust-crates/futures-macro-0.3.31
	rust-crates/futures-sink-0.3.31
	rust-crates/futures-task-0.3.31
	rust-crates/futures-util-0.3.31
	rust-crates/getrandom-0.3.4
	rust-crates/heck-0.5.0
	rust-crates/ident_case-1.0.1
	rust-crates/indicatif-0.18.3
	rust-crates/indoc-2.0.7
	rust-crates/is_terminal_polyfill-1.70.2
	rust-crates/itertools-0.14.0
	rust-crates/itoa-1.0.15
	rust-crates/jiff-0.2.16
	rust-crates/jiff-static-0.2.16
	rust-crates/js-sys-0.3.83
	rust-crates/libc-0.2.177
	rust-crates/linux-raw-sys-0.11.0
	rust-crates/log-0.4.28
	rust-crates/macro_rules_attribute-0.2.2
	rust-crates/macro_rules_attribute-proc_macro-0.2.2
	rust-crates/matrixmultiply-0.3.10
	rust-crates/memchr-2.7.6
	rust-crates/memoffset-0.9.1
	rust-crates/minimal-lexical-0.2.1
	rust-crates/mio-1.1.0
	rust-crates/monostate-0.1.18
	rust-crates/monostate-impl-0.1.18
	rust-crates/ndarray-0.16.1
	rust-crates/nom-7.1.3
	rust-crates/num-complex-0.4.6
	rust-crates/num-integer-0.1.46
	rust-crates/num-traits-0.2.19
	rust-crates/numpy-0.26.0
	rust-crates/once_cell-1.21.3
	rust-crates/once_cell_polyfill-1.70.2
	rust-crates/onig-6.5.1
	rust-crates/onig_sys-69.9.1
	rust-crates/paste-1.0.15
	rust-crates/pin-project-lite-0.2.16
	rust-crates/pin-utils-0.1.0
	rust-crates/pkg-config-0.3.32
	rust-crates/portable-atomic-1.11.1
	rust-crates/portable-atomic-util-0.2.4
	rust-crates/ppv-lite86-0.2.21
	rust-crates/proc-macro2-1.0.103
	rust-crates/pyo3-0.26.0
	rust-crates/pyo3-async-runtimes-0.26.0
	rust-crates/pyo3-build-config-0.26.0
	rust-crates/pyo3-ffi-0.26.0
	rust-crates/pyo3-macros-0.26.0
	rust-crates/pyo3-macros-backend-0.26.0
	rust-crates/quote-1.0.42
	rust-crates/r-efi-5.3.0
	rust-crates/rand-0.9.2
	rust-crates/rand_chacha-0.9.0
	rust-crates/rand_core-0.9.3
	rust-crates/rawpointer-0.2.1
	rust-crates/rayon-1.11.0
	rust-crates/rayon-cond-0.4.0
	rust-crates/rayon-core-1.13.0
	rust-crates/regex-1.12.2
	rust-crates/regex-automata-0.4.13
	rust-crates/regex-syntax-0.8.8
	rust-crates/rustc-hash-2.1.1
	rust-crates/rustix-1.1.2
	rust-crates/rustversion-1.0.22
	rust-crates/ryu-1.0.20
	rust-crates/serde-1.0.228
	rust-crates/serde_core-1.0.228
	rust-crates/serde_derive-1.0.228
	rust-crates/serde_json-1.0.145
	rust-crates/shlex-1.3.0
	rust-crates/signal-hook-registry-1.4.7
	rust-crates/slab-0.4.11
	rust-crates/smallvec-1.15.1
	rust-crates/spm_precompiled-0.1.4
	rust-crates/static_assertions-1.1.0
	rust-crates/strsim-0.11.1
	rust-crates/syn-2.0.111
	rust-crates/target-lexicon-0.13.3
	rust-crates/tempfile-3.23.0
	rust-crates/thiserror-2.0.17
	rust-crates/thiserror-impl-2.0.17
	rust-crates/tokio-1.48.0
	rust-crates/tokio-macros-2.6.0
	rust-crates/unicode-ident-1.0.22
	rust-crates/unicode-normalization-alignments-0.1.12
	rust-crates/unicode-segmentation-1.12.0
	rust-crates/unicode-width-0.2.2
	rust-crates/unicode_categories-0.1.1
	rust-crates/unindent-0.2.4
	rust-crates/unit-prefix-0.5.2
	rust-crates/utf8parse-0.2.2
	rust-crates/version_check-0.9.5
	rust-crates/wasi-0.11.1+wasi-snapshot-preview1
	rust-crates/wasip2-1.0.1+wasi-0.2.4
	rust-crates/wasm-bindgen-0.2.106
	rust-crates/wasm-bindgen-macro-0.2.106
	rust-crates/wasm-bindgen-macro-support-0.2.106
	rust-crates/wasm-bindgen-shared-0.2.106
	rust-crates/web-time-1.1.0
	rust-crates/windows-link-0.2.1
	rust-crates/windows-sys-0.61.2
	rust-crates/wit-bindgen-0.46.0
	rust-crates/zerocopy-0.8.31
	rust-crates/zerocopy-derive-0.8.31
"
# lockstep-cargo-deps: end

# Autogenerated by pycargoebuild 0.15.0

DISTUTILS_USE_PEP517=maturin
PYTHON_COMPAT=( python3_{10..13} )
DISTUTILS_EXT=1
DISTUTILS_SINGLE_IMPL=1
RUST_MIN_VER="1.82.0"

CRATES="
"

inherit cargo lockstep-cargo distutils-r1
# lockstep-pypi-managed: true
# lockstep-pypi-deps: begin
RDEPEND+="
	dev-python/huggingface_hub
"
# lockstep-pypi-deps: end

DESCRIPTION="Implementation of today's most used tokenizers"
HOMEPAGE="https://github.com/huggingface/tokenizers"
SRC_URI="
	https://github.com/huggingface/${PN}/archive/refs/tags/v${PV}.tar.gz
	-> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="Apache-2.0"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD ISC MIT MPL-2.0
	Unicode-DFS-2016
"
SLOT="0"
KEYWORDS="amd64 arm64"

RDEPEND="dev-libs/oniguruma"
BDEPEND="
	test? ( dev-python/datasets[${PYTHON_SINGLE_USEDEP}] )
	$(python_gen_cond_dep '
		dev-py/setuptools-rust[${PYTHON_USEDEP}]
	')
"

distutils_enable_tests pytest

QA_FLAGS_IGNORED=".*/site-packages/tokenizers/.*so"

src_unpack() {
	cargo_src_unpack
}

pkg_setup() {
	python-single-r1_pkg_setup
	rust_pkg_setup
}

src_prepare() {
	default
	cd bindings/python
	eapply "${FILESDIR}"/${PN}-0.21.2-test.patch
	distutils-r1_src_prepare
}

src_configure() {
	cd tokenizers
	cargo_src_configure
	cd ../bindings/python
	distutils-r1_src_configure
}

src_compile() {
	export RUSTONIG_SYSTEM_LIBONIG=1
	cd tokenizers
	cargo_src_compile
	cd ../bindings/python
	distutils-r1_src_compile
}

src_test() {
	cd tokenizers
	# Tests do not work
	#cargo_src_test
	cd ../bindings/python
	local -x EPYTEST_IGNORE=( benches/ )
	local -x EPYTEST_DESELECT=(
		tests/bindings/test_encoding.py::TestEncoding::test_sequence_ids
		tests/bindings/test_encoding.py::TestEncoding::test_n_sequences
		tests/bindings/test_encoding.py::TestEncoding::test_word_to_tokens
		tests/bindings/test_encoding.py::TestEncoding::test_word_to_chars
		tests/bindings/test_encoding.py::TestEncoding::test_token_to_sequence
		tests/bindings/test_encoding.py::TestEncoding::test_token_to_chars
		tests/bindings/test_encoding.py::TestEncoding::test_token_to_word
		tests/bindings/test_encoding.py::TestEncoding::test_char_to_token
		tests/bindings/test_encoding.py::TestEncoding::test_char_to_word
		tests/bindings/test_encoding.py::TestEncoding::test_truncation
		tests/bindings/test_encoding.py::TestEncoding::test_invalid_truncate_direction
		tests/bindings/test_models.py::TestBPE::test_instantiate
		tests/bindings/test_models.py::TestWordLevel::test_instantiate
		tests/bindings/test_models.py::TestWordPiece::test_instantiate
		tests/bindings/test_processors.py::TestByteLevelProcessing::test_processing
		tests/bindings/test_trainers.py::TestUnigram::test_continuing_prefix_trainer_mismatch
		tests/bindings/test_trainers.py::TestUnigram::test_train
		tests/bindings/test_trainers.py::TestUnigram::test_train_parallelism_with_custom_pretokenizer
		tests/documentation/test_pipeline.py::TestPipeline::test_pipeline
		tests/documentation/test_pipeline.py::TestPipeline::test_bert_example
		tests/implementations/test_char_bpe.py::TestCharBPETokenizer::test_basic_encode
		tests/implementations/test_char_bpe.py::TestCharBPETokenizer::test_lowercase
		tests/implementations/test_char_bpe.py::TestCharBPETokenizer::test_decoding
		tests/implementations/test_char_bpe.py::TestCharBPETokenizer::test_multiprocessing_with_parallelism
		tests/test_serialization.py::TestSerialization::test_full_serialization_albert
		tests/test_serialization.py::TestSerialization::test_str_big
		tests/bindings/test_tokenizer.py::TestTokenizer::test_encode_formats
		tests/bindings/test_tokenizer.py::TestTokenizer::test_encode_add_special_tokens
		tests/bindings/test_tokenizer.py::TestTokenizer::test_from_pretrained
		tests/bindings/test_tokenizer.py::TestTokenizer::test_from_pretrained_revision
		tests/bindings/test_tokenizer.py::TestTokenizer::test_encode_special_tokens
		tests/bindings/test_tokenizer.py::TestTokenizer::test_splitting
		tests/documentation/test_quicktour.py::TestQuicktour::test_quicktour
		tests/documentation/test_tutorial_train_from_iterators.py::TestTrainFromIterators::test_datasets
		tests/documentation/test_tutorial_train_from_iterators.py::TestTrainFromIterators::test_gzip
		tests/implementations/test_bert_wordpiece.py::TestBertWordPieceTokenizer::test_basic_encode
		tests/implementations/test_bert_wordpiece.py::TestBertWordPieceTokenizer::test_multiprocessing_with_parallelism
		tests/implementations/test_byte_level_bpe.py::TestByteLevelBPE::test_basic_encode
		tests/implementations/test_byte_level_bpe.py::TestByteLevelBPE::test_add_prefix_space
		tests/implementations/test_byte_level_bpe.py::TestByteLevelBPE::test_lowerspace
		tests/implementations/test_byte_level_bpe.py::TestByteLevelBPE::test_multiprocessing_with_parallelism

	)
	distutils-r1_src_test
}

src_install() {
	cd tokenizers
	cd ../bindings/python
	distutils-r1_src_install
}
