#!/bin/sh

# 1g4 Linux fork of xvfb-run by Branden Robinson and Jeff Licquia.
# Distributed under GPL-2 or later; see LICENSE and ../README.md.

set -e

PROGNAME=xvfb-run
SERVERNUM=99
AUTHFILE=
ERRORFILE=/dev/null
XVFBARGS="-screen 0 1280x1024x24"
LISTENTCP="-nolisten tcp"
XAUTHPROTO=.
XVFB_RUN_TMPDIR=
XVFBPID=
AUTONUM=
SHOWHELP=

message () {
    printf '%s: %s\n' "$PROGNAME" "$*"
}

# Display an error message.
error () {
    message "error: $*" >&2
}

# Display a usage message.
usage () {
    if [ -n "$*" ]; then
        message "usage error: $*"
    fi
    cat <<EOF
Usage: $PROGNAME [OPTION ...] COMMAND
Run COMMAND (usually an X client) in a virtual X server environment.
Options:
-a        --auto-servernum          try to get a free server number, starting at
                                    --server-num
-e FILE   --error-file=FILE         file used to store xauth errors and Xvfb
                                    output (default: $ERRORFILE)
-f FILE   --auth-file=FILE          file used to store auth cookie
                                    (default: a private temporary file)
-h        --help                    display this usage message and exit
-n NUM    --server-num=NUM          server number to use (default: $SERVERNUM)
-l        --listen-tcp              enable TCP port listening in the X server
-p PROTO  --xauth-protocol=PROTO    X authority protocol name to use
                                    (default: xauth command's default)
-s ARGS   --server-args=ARGS        arguments (other than server number and
                                    "-nolisten tcp") to pass to the Xvfb server
                                    (default: "$XVFBARGS")
EOF
}

# Find a free server number by looking at .X*-lock files in /tmp.
find_free_servernum() {
    i=$SERVERNUM
    while [ -f /tmp/.X$i-lock ]; do
        i=$(($i + 1))
    done
    echo $i
}

# Clean up files
clean_up() {
    status=$?
    trap - EXIT
    if [ -n "$XVFBPID" ]; then
        kill "$XVFBPID" >&3 2>&3 || :
        wait "$XVFBPID" 2>/dev/null || :
    fi
    if [ -e "$AUTHFILE" ]; then
        XAUTHORITY=$AUTHFILE xauth remove ":$SERVERNUM" >&3 2>&3 || :
    fi
    if [ -n "$XVFB_RUN_TMPDIR" ]; then
        if ! rm -r "$XVFB_RUN_TMPDIR"; then
            error "problem while cleaning up temporary directory"
            [ "$status" -ne 0 ] || status=5
        fi
    fi
    exit "$status"
}

# Parse the command line.
if ARGS=$(getopt --options +ae:f:hn:lp:s:w: \
       --long auto-servernum,error-file:,auth-file:,help,server-num:,listen-tcp,xauth-protocol:,server-args:,wait: \
       --name "$PROGNAME" -- "$@"); then
    :
else
    error "invalid command-line options"
    exit 6
fi

eval set -- "$ARGS"

while :; do
    case "$1" in
        -a|--auto-servernum) AUTONUM="yes" ;;
        -e|--error-file) ERRORFILE="$2"; shift ;;
        -f|--auth-file) AUTHFILE="$2"; shift ;;
        -h|--help) SHOWHELP="yes" ;;
        -n|--server-num) SERVERNUM="$2"; shift ;;
        -l|--listen-tcp) LISTENTCP="" ;;
        -p|--xauth-protocol) XAUTHPROTO="$2"; shift ;;
        -s|--server-args) XVFBARGS="$2"; shift ;;
        -w|--wait) shift ;;
        --) shift; break ;;
        *) error "internal error; getopt permitted \"$1\" unexpectedly"
           exit 6
           ;;
    esac
    shift
done

if [ "$SHOWHELP" ]; then
    usage
    exit 0
fi

if [ "$#" -eq 0 ]; then
    usage "need a command to run" >&2
    exit 2
fi

for tool in Xvfb xauth mcookie; do
    if ! command -v "$tool" >/dev/null; then
        error "$tool command not found"
        exit 3
    fi
done

case "$SERVERNUM" in
    ''|*[!0-9]*)
        error "server number must be a nonnegative integer"
        exit 2
        ;;
esac
while [ "${SERVERNUM#0}" != "$SERVERNUM" ] && [ "$SERVERNUM" != 0 ]; do
    SERVERNUM=${SERVERNUM#0}
done
if [ -n "$AUTONUM" ]; then
    SERVERNUM=$(find_free_servernum)
fi

# Open fd 3 for diagnostic output from Xvfb, etc.
case "$ERRORFILE" in
    (/proc/self/fd/1 | /dev/stdout)
        # We might not actually be able to write to this if it's a file or
        # terminal owned by someone else, so duplicate the fd instead
        exec 3>&1
        ;;
    (/proc/self/fd/2 | /dev/stderr)
        # See above
        exec 3>&2
        ;;
    (*)
        exec 3>>"$ERRORFILE"
        ;;
esac

# tidy up after ourselves
trap clean_up EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

# If the user did not specify an X authorization file to use, set up a temporary
# directory to house one.
if [ -z "$AUTHFILE" ]; then
    XVFB_RUN_TMPDIR="$(mktemp -d "${TMPDIR:-/tmp}/$PROGNAME.XXXXXX")"
    AUTHFILE="$XVFB_RUN_TMPDIR/Xauthority"
    # Create empty file to avoid xauth warning
    touch "$AUTHFILE"
fi

# Start Xvfb.
MCOOKIE=$(mcookie)
tries=10
while [ $tries -gt 0 ]; do
    tries=$(( $tries - 1 ))
    XAUTHORITY=$AUTHFILE xauth source - << EOF >&3 2>&3
add :$SERVERNUM $XAUTHPROTO $MCOOKIE
EOF
    # handle SIGUSR1 so Xvfb knows to send a signal when it's ready to accept
    # connections
    trap : USR1
    # Split server arguments on whitespace, but do not expand pathname patterns.
    (trap '' USR1; set -f; exec Xvfb ":$SERVERNUM" $XVFBARGS $LISTENTCP -auth "$AUTHFILE" >&3 2>&3 3>&-) &
    XVFBPID=$!

    wait "$XVFBPID" || :
    if kill -0 "$XVFBPID" 2>/dev/null; then
        break
    fi
    XVFBPID=
    XAUTHORITY=$AUTHFILE xauth remove ":$SERVERNUM" >&3 2>&3 || :
    if [ -n "$AUTONUM" ]; then
        # The display is in use so try another one (if '-a' was specified).
        SERVERNUM=$((SERVERNUM + 1))
        SERVERNUM=$(find_free_servernum)
        continue
    fi
    error "Xvfb failed to start"
    exit 1
done
if [ -z "$XVFBPID" ]; then
    error "Xvfb failed to start after 10 attempts"
    exit 1
fi

# Start the command and save its exit status.
set +e
DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 3>&-
RETVAL=$?
set -e

# Return the executed command's exit status.
exit $RETVAL
