#!/bin/bash

mkdir -p /tmp/bp_backup
cp -rp /var/db/repos/bp /tmp/bp_backup/

rm -rf /tmp/bp_backup/bp/bin
rm -rf /tmp/bp_backup/bp/app-emu/qemu
rm -rf /tmp/bp_backup/bp/lib-dev/boost*
rm -rf /tmp/bp_backup/bp/xgui-live-app/ethminer
rm -rf /tmp/bp_backup/bp/app-build/gcc
rm -rf /tmp/bp_backup/bp/app-tex/ghostscript-gpl

find /tmp/bp_backup/bp -type f -name 'Manifest' -delete

(cd /tmp/bp_backup/bp && pkgdev manifest)

rm -rf /tmp/bp_backup
