#!/bin/bash

cp -L /etc/resolv.conf etc/
mount -t proc proc proc
mount --rbind /sys sys
mount --make-rslave sys
mount --rbind /dev dev
mount --make-rslave dev
mount -t tmpfs -o nosuid,nodev,noexec shm /dev/shm
chmod 1777 /dev/shm
chroot .
source /etc/profile
export PS1="(chroot) $PS1"
