# lockstep-managed: cargo-crate
EAPI=8
MERGE_MANIFEST_MODE="tree-blake3-v1"

CRATE_NAME="rusqlite"
CRATE_VERSION="0.40.1"
CRATE_CHECKSUM="11438310b19e3109b6446c33d1ed5e889428cf2e278407bc7896bc4aaea43323"
CRATE_SOURCE="registry+https://github.com/rust-lang/crates.io-index"
CRATE_SOURCE_KIND="registry"

inherit cargo-crate

DESCRIPTION="Ergonomic wrapper for SQLite"
HOMEPAGE="https://github.com/rusqlite/rusqlite"
LICENSE="MIT"
SLOT="${PV}"
KEYWORDS="amd64 arm64"

CARGO_CRATE_FEATURES=(
	"array"
	"backup"
	"blob"
	"buildtime_bindgen"
	"bundled"
	"bundled-full"
	"bundled-sqlcipher"
	"bundled-sqlcipher-vendored-openssl"
	"bundled-windows"
	"cache"
	"collation"
	"column_decltype"
	"column_metadata"
	"csvtab"
	"default"
	"extra_check"
	"fallible_uint"
	"ffi-sqlite-wasm-rs"
	"functions"
	"hooks"
	"i128_blob"
	"in_gecko"
	"limits"
	"load_extension"
	"loadable_extension"
	"modern-full"
	"modern_sqlite"
	"pointer"
	"preupdate_hook"
	"serialize"
	"series"
	"session"
	"sqlcipher"
	"trace"
	"unlock_notify"
	"vtab"
	"wasm32-wasi-vfs"
	"window"
	"with-asan"
)
