#!/bin/bash

set -e
shopt -s nullglob

for videofile in *.mkv ; do
	if [[ $videofile != *.raw.mkv ]] && [ ! -f "${videofile%.*}.m4a" ]; then
		ffmpeg -n -i "$videofile" -dn -sn -vn -c:a aac -q:a 2 "${videofile%.*}.m4a"
	fi
done
