#!/bin/bash

for videofile in *.m4a ; do
	if [ ! -f "${videofile%.*}-muxed.mp4" ]; then
		ffmpeg -i "${videofile%.*}.raw.mkv" -i "${videofile%.*}.m4a" -c copy -c:s mov_text -movflags +faststart "${videofile%.*}-muxed.mp4"
	fi
done
