#!/bin/bash

mv /var/db/repos/bp/.git /var/db/repos/git_backup

find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\$\(get_libdir\)/lib/g'

find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-arch/app-compression/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-lang/app-lang/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-lang\/perl/app-lang\/perl/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-util\/cmake/app-dev\/cmake/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/media-libs\/fontconfig/fonts\/fontconfig/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-apps\/kmod/app-core\/kmod/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-apps\/sed/app-core\/sed/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-devel\/bc/app-build\/bc/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-devel\/bison/app-build\/bison/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-devel\/flex/app-build\/flex/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-devel\/make/app-build\/make/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-libs\/ncurses/lib-core\/ncurses/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/virtual\/libelf/lib-core\/elfutils/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/virtual\/linux-sources/app-kernel\/xanmod-sources/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/virtual\/pkgconfig/app-dev\/pkgconf/g'

find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-util\/desktop-file-utils/xgui-misc\/desktop-file-utils/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/x11-misc\/shared-mime-info/xgui-live-app\/shared-mime-info/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-libs\/glib/lib-live\/glib/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-util/app-dev/g'

mv /var/db/repos/git_backup /var/db/repos/bp/.git
