#!/bin/bash

TEMPLOCATION="/tmp/eclass_import"
mkdir -p "${TEMPLOCATION}"
[ ! -d "${TEMPLOCATION}/gentoo" ] && git clone https://github.com/gentoo/gentoo.git "${TEMPLOCATION}/gentoo" --depth 1
cp "${TEMPLOCATION}"/gentoo/eclass/{autotools,cargo,cmake,crossdev,distutils-r1,estack,flag-o-matic,font,git-r3,gnuconfig,go-env,go-module,kernel-2,libtool,linux-info,linux-mod,meson,multibuild,multiprocessing,ninja-utils,optfeature,perl-functions,perl-module,out-of-source-utils,prefix,python*,qmake-utils,sgml-catalog-r1,toolchain-funcs,unpacker,user-info,xdg,xdg-utils,wrapper}.eclass /var/db/repos/bp/eclass/

find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/dosym8/d'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/einstalldocs/d'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ eapi8-dosym/d'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ eqawarn/d'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ eutils/d'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i '/inherit\ multilib/d'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\ multilib//g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\ readme.gentoo-r1//g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\$(get_libdir)/lib/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-arch/app-compression/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-portage/app-port/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-text/app-tex/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-lang/app-lang/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-libs\/glib/lib-live\/glib/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-util\/desktop-file-utils/xgui-misc\/desktop-file-utils/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-util/app-dev/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/dev-vcs\/git/app-core\/git/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/media-fonts\/encodings/fonts\/encodings/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/media-libs\/fontconfig/fonts\/fontconfig/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-apps/app-core/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-devel/app-build/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/sys-libs/lib-core/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/virtual\/libelf/lib-core\/elfutils/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/virtual\/pkgconfig/app-dev\/pkgconf/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/x11-apps\/mkfontscale/xgui-live-app\/mkfontscale/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/x11-misc\/shared-mime-info/xgui-live-app\/shared-mime-info/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\${EPREFIX}\$\(qt5_get_libdir\)\/qt5\/bin/\/usr\/bin/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/\$(get_abi_LDFLAGS)/\${LDFLAGS}/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/get_abi_CHOST/CHOST/g'
find /var/db/repos/bp/eclass -type f -print0 | xargs -0 sed -i 's/app-dev\/ninja/app-dev\/samurai/g'

sed -i 's/.*qt5\/bin.*/	echo\ \/usr\/bin/' /var/db/repos/bp/eclass/qmake-utils.eclass

sed -i 's/var\/lib/var/' /var/db/repos/bp/eclass/meson.eclass

#insert on 3rd line
sed -i '3i\PYTHON_COMPAT=( python3_11 python3_12 )\' /var/db/repos/bp/eclass/python-utils-r1.eclass
