#!/bin/bash

if [ $(id -u) = 0 ]; then
	#portage
	mkdir -p /var/db/repos /var/cache/{distfiles,packages}
	chown -hR portage: /var/cache/{distfiles,packages}
	find /var/db/repos -type d -exec chmod 755 {} +
	find /var/db/repos -type f -exec chmod 644 {} +

	#eix
	mkdir -p /var/cache/eix
	[ ! -f "/var/cache/eix/portage.eix" ] && touch "/var/cache/eix/portage.eix"
	chown portage: /var/cache/eix/portage.eix

	#http
	find /srv/http -type d -exec chmod 755 {} +
	find /srv/http -type f -exec chmod 644 {} +
	[ -d /var/lighttpd ] && find /var/lighttpd -type d -exec chmod 755 {} +
	[ -d /var/lighttpd ] && find /var/lighttpd -type f -exec chmod 644 {} +

	#users and groups files
	chmod 600 /etc/{gshadow,shadow}
	chmod 644 /etc/{group,passwd}
fi

#permissions for everyone
find $HOME/.ssh -type d -exec chmod 700 {} +
find $HOME/.ssh -type f -exec chmod 600 {} +
[ -f $HOME/.ssh/authorized_keys ] && chmod 644 $HOME/.ssh/authorized_keys
chown -R $(id -u):$(id -g) $HOME/.ssh
