#!/bin/bash

mkdir -p /var/db/repos /var/cache/{distfiles,packages}
mkdir -p /var/cache/eix

chown -hR portage: /var/cache/{distfiles,packages}
chown portage: /var/cache/eix/portage.eix

emerge --sync

echo "Regenerating bp repo cache..." && egencache --jobs=4 --update --repo bp

emerge --regen
emerge --metadata
eix-update
