#!/bin/bash

echo "Syncing the bp repository..."
pmaint sync bp || { echo "Failed to sync repository."; }

echo "Regenerating bp repository cache..."
pmaint regen bp || { echo "Failed to regenerate cache for repository"; exit 1; }

echo "Updating the eix database..."
eix-update
