#!/bin/bash

echo "Regenerating bp repo cache..."
for dir in /var/db/repos/*/
do
    dir=${dir%*/} # remove the trailing "/"
    egencache --jobs=8 --update --repo "${dir##*/}" # remove full path
done

emerge --regen
emerge --metadata
eix-update
