#!/bin/bash

RANDOMSTRING="$(cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-5} | head -n 1)"
WORKHOME="${HOME}/gnu_tarballs"
TEMPLOCATION="${WORKHOME}/tmp"

mkdir -p ${TEMPLOCATION}
cd ${WORKHOME}

git clone https://github.com/coreutils/gnulib.git ${WORKHOME}/gnulib
git clone https://github.com/coreutils/coreutils.git ${WORKHOME}/coreutils

for i in coreutils gperf patch libtool diffutils findutils grep tar sed ; do
	git clone https://git.savannah.gnu.org/git/$i.git ${WORKHOME}/$i
	GITDATENAME="$i-$(cd ${WORKHOME}/$i && git log -1 --format="%at" | xargs -I{} date -d @{} +%Y%m%d)"
	(cd ${WORKHOME}/gnulib && git remote update )
	( cd ${WORKHOME}/$i && git remote update )
	( cd ${WORKHOME}/$i && rm -rf gnulib )
	( cd ${WORKHOME}/$i && ln -s ../gnulib gnulib )
	( cd ${WORKHOME}/$i && ./bootstrap || ./autogen.sh )
	tar -hcf - $i | tar -xf - -C ${TEMPLOCATION}
	mv ${TEMPLOCATION}/$i ${TEMPLOCATION}/${GITDATENAME}
	find ${TEMPLOCATION}/${GITDATENAME} -name *~ -delete
	( cd ${TEMPLOCATION}/${GITDATENAME} && rm -rf .git* gnulib autom4te.cache po/.reference )
	find ${TEMPLOCATION}/${GITDATENAME} -name *.git* -delete
	( cd ${TEMPLOCATION} && XZOPT=-e9 tar cJf ${WORKHOME}/${GITDATENAME}.tar.xz ${GITDATENAME} --owner=0 --group=0 )
done

rm -rf ${TEMPLOCATION}
