#!/bin/bash

RANDOMSTRING="$(cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-5} | head -n 1)"
WORKHOME="${HOME}/gnu_tarballs"
TEMPLOCATION="${WORKHOME}/tmp"

rm -rf ${TEMPLOCATION}
mkdir -p ${TEMPLOCATION}
cd ${WORKHOME}

git clone https://github.com/coreutils/gnulib.git ${WORKHOME}/gnulib
git clone https://github.com/coreutils/coreutils.git ${WORKHOME}/coreutils

#special patch build
for i in patch ; do
	git clone https://git.savannah.gnu.org/git/$i.git ${WORKHOME}/$i
	GITDATENAME="$i-$(cd ${WORKHOME}/$i && git log -1 --format="%at" | xargs -I{} date -d @{} +%Y%m%d)"
	( cd ${WORKHOME}/$i && git remote update )
	cp -rp ${WORKHOME}/gnulib ${WORKHOME}/gnulib_patch
	( cd ${WORKHOME}/gnulib_patch && git reset --hard b141afaf9ba197e361510da075556822ac453ff6 )
	( cd ${WORKHOME}/$i && ./bootstrap --skip-po --no-git --gnulib-srcdir=${WORKHOME}/gnulib_patch )
	tar -hcf - $i | tar -xf - -C ${TEMPLOCATION}
	mv ${TEMPLOCATION}/$i ${TEMPLOCATION}/${GITDATENAME}
	find ${TEMPLOCATION}/${GITDATENAME} -name *~ -delete
	( cd ${TEMPLOCATION}/${GITDATENAME} && rm -rf .git* gnulib autom4te.cache po/.reference )
	find ${TEMPLOCATION}/${GITDATENAME} -name *.git* -delete
	( cd ${TEMPLOCATION} && XZOPT=-e9 tar cJf ${WORKHOME}/${GITDATENAME}.tar.xz ${GITDATENAME} --owner=0 --group=0 )
done

for i in coreutils gperf libtool diffutils findutils grep tar sed ; do
	git clone https://git.savannah.gnu.org/git/$i.git ${WORKHOME}/$i
	GITDATENAME="$i-$(cd ${WORKHOME}/$i && git log -1 --f="%at" | xargs -I{} date -d @{} +%Y%m%d)"
	(cd ${WORKHOME}/gnulib && git remote update )
	( cd ${WORKHOME}/$i && git remote update )
	( cd ${WORKHOME}/$i && rm -rf gnulib )
	( cd ${WORKHOME}/$i && ln -s ../gnulib gnulib )
	( cd ${WORKHOME}/$i && ./bootstrap --skip-po --no-git --gnulib-srcdir=${WORKHOME}/gnulib || ./autogen.sh )
	tar -hcf - $i | tar -xf - -C ${TEMPLOCATION}
	mv ${TEMPLOCATION}/$i ${TEMPLOCATION}/${GITDATENAME}
	find ${TEMPLOCATION}/${GITDATENAME} -name *~ -delete
	( cd ${TEMPLOCATION}/${GITDATENAME} && rm -rf .git* gnulib autom4te.cache po/.reference )
	find ${TEMPLOCATION}/${GITDATENAME} -name *.git* -delete
	( cd ${TEMPLOCATION} && XZOPT=-e9 tar cJf ${WORKHOME}/${GITDATENAME}.tar.xz ${GITDATENAME} --owner=0 --group=0 )
done

rm -rf ${TEMPLOCATION}
