#!/bin/bash

UP_PYTHON="upPython"
UP_GIT="upGit"
UP_BROWSERS="upBrowsers"
UP_APP="upApp"
UP_DAY="/tmp/upGit/upDay"

echo "Running upPython..."
"$UP_PYTHON"

echo "Running upGit..."
"$UP_GIT"

echo "Running upBrowsers..."
"$UP_BROWSERS"

echo "Running upApp..."
"$UP_APP"

echo "Executing upDay from temporary location..."
"$UP_DAY"

echo "All scripts executed successfully."
