#!/bin/bash

PACKAGES=(
	"ConfigArgParse"
	"PySocks"
	"appdirs"
	"autocommand"
	"backports-tarfile"
	"boltons"
	"build"
	"certifi"
	"cffi"
	"chardet"
	"charset-normalizer"
	"colorama"
	"configobj"
	"coverage"
	"cryptography"
	"cython"
	"distlib"
	"distro"
	"docutils"
	"editables"
	"ensurepip-pip"
	"execnet"
	"fastjsonschema"
	"filelock"
	"flit-core"
	"gpep517"
	"hatch-vcs"
	"hatchling"
	"idna"
	"importlib-metadata"
	"ini2toml"
	"iniconfig"
	"installer"
	"jaraco-context"
	"jaraco-env"
	"jaraco-envs"
	"jaraco-functools"
	"jaraco-path"
	"jaraco-text"
	"jinja"
	"josepy"
	"lark"
	"lazy-object-proxy"
	"lxml"
	"mako"
	"markupsafe"
	"maturin"
	"more-itertools"
	"olefile"
	"ordered-set"
	"packaging"
	"parsedatetime"
	"path"
	"pathspec"
	"pillow"
	"pip"
	"pip-run"
	"platformdirs"
	"pluggy"
	"ply"
	"poetry-core"
	"psutil"
	"py"
	"pycparser"
	"pyelftools"
	"pygments"
	"pyopenssl"
	"pyproject-hooks"
	"pyrfc3339"
	"pytest"
	"pytest-cov"
	"pytest-home"
	"pytest-timeout"
	"pytest-xdist"
	"pytz"
	"pyxdg"
	"pyyaml"
	"requests"
	"requests-toolbelt"
	"semantic-version"
	"setuptools"
	"setuptools-rust"
	"setuptools-scm"
	"six"
	"snakeoil"
	"tomli"
	"tomli-w"
	"tree-sitter"
	"trove-classifiers"
	"typing-extensions"
	"urllib3"
	"virtualenv"
	"wheel"
	"zipp"
	"zstandard"
)

GENTOO_PATH="/tmp/gentoo-repo"
PACKAGE_DIR="/var/db/repos/bp/dev-python"
REPO="https://github.com/gentoo/gentoo.git"

finalize_update() {
	local package_path="$1"
	local package_name="$2"
	local new_ebuild_filename="$3"
	local version="$4"

	if ! (cd "$package_path" && pkgdev manifest); then
		echo "Error generating manifest for ${package_name}. Skipping..."
		return 1
	fi

	(cd "$package_path" && \
			git add --all . > /dev/null 2>&1 && \
			git -c user.name="${BOT_USER}" \
			-c user.email="${BOT_EMAIL}" \
			-c commit.gpgsign=true \
			-c user.signingkey="${BOT_KEYID}" \
			commit -m "Update ${package_name} to ${version}" > /dev/null 2>&1 && \
		git push origin HEAD > /dev/null 2>&1)

	echo "Ebuild updated for ${package_name}: ${new_ebuild_filename}"
}

echo "Starting script execution..."
echo "Removing the existing ${PACKAGE_DIR} directory to start fresh..."
rm -rf "${PACKAGE_DIR}"

echo "Creating directory at ${PACKAGE_DIR}..."
mkdir -p "${PACKAGE_DIR}"
echo "Directory created or already exists."

if [ -d "${GENTOO_PATH}" ]; then
	echo "Updating the Gentoo package repository in ${GENTOO_PATH}..."
	cd "${GENTOO_PATH}" && git pull
else
	echo "Cloning the Gentoo package repository to ${GENTOO_PATH}..."
	git clone "${REPO}" "${GENTOO_PATH}" --depth 1
fi

echo "Repository setup complete."

echo "Starting package copy process..."

for package in "${PACKAGES[@]}"; do
	src_path="${GENTOO_PATH}/dev-python/${package}"
	dest_path="${PACKAGE_DIR}/${package}"

	echo "Processing ${package}..."
	if [ -d "${src_path}" ]; then
		echo "Copying ${package} from ${src_path} to ${dest_path}..."
		cp -R "${src_path}" "${dest_path}"
		echo "Copy complete for ${package}."
	else
		echo "Package dev-python/${package} not found in the repository."
	fi
done

echo "Package copy process completed."

echo "Starting cleanup process..."

[ -d "${PACKAGE_DIR}/gpep517" ] && echo "Updating EAPI for gpep517..." && find "${PACKAGE_DIR}/gpep517" -type f -name "*.ebuild" -exec sed -i'' 's/EAPI=7/EAPI=8/' {} + && echo "EAPI updated for gpep517."

echo "Removing files ending with 9999.ebuild in ${PACKAGE_DIR}..."
find "${PACKAGE_DIR}" -type f -name '*9999.ebuild' -exec echo "Deleting {}" \; -delete

echo "Removing lines containing 'Gentoo Authors' from files in ${PACKAGE_DIR}..."
find "${PACKAGE_DIR}" -type f -exec sed -i'' '/Gentoo Authors/d' {} \;

echo "Removing metadata.xml files from ${PACKAGE_DIR}..."
find "${PACKAGE_DIR}" -type f -name 'metadata.xml' -exec echo "Deleting {}" \; -delete

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec sed -i'' '/newbashcomp/d' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec sed -i'' 'N;/^\n$/!P;D' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec sed -i'' \
	-e '/dev-vcs\/mercurial/d' \
	-e '/dev-vcs\/git/d' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec perl -i'' -0777 -pe '
    s/!sparc\?\s*\(([^()]|\n)*\)//g;
' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec perl -i'' -0777 -pe '
    s/!hppa\?\s*\(([^()]|\n)*\)//g;
' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec sed -i'' '/!hppa? (/,+4d' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec perl -i'' -0777 -pe '
    s/!s390\?\s*\(([^()]|\n)*\)//g;
' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec perl -i'' -0777 -pe '
    s/test\?\s*\(\s*\)//g;
' {} +

find "${PACKAGE_DIR}" -type f -name "*.ebuild" -exec perl -i'' -0777 -pe '
    s/test-rust\?\s*\(\s*\)//g;
' {} +

find "${PACKAGE_DIR}" -type f -name '*_rc[1-9].ebuild' -exec echo "Deleting _rc ebuild: {}" \; -delete
find "${PACKAGE_DIR}" -type f -name '*_pre*.ebuild' -exec echo "Deleting _pre ebuild: {}" \; -delete

for package in cython psutil lxml cffi pillow tree-sitter zstandard; do
	if [ -d "${PACKAGE_DIR}/${package}" ]; then
		echo "Updating for ${package}..."
		find "${PACKAGE_DIR}/${package}" -type f -name "*.ebuild" -exec sh -c '
            for ebuild_file; do
                echo "Processing $ebuild_file"
                if grep -q "^python_compile()" "$ebuild_file"; then
                    echo "Adding line to python_compile in $ebuild_file"
                    sed -i "/^python_compile()/ { N; s|\\n|\\n\\tfilter-flags -Wl,-z,defs\\n| }" "$ebuild_file"
                fi
                if grep -q "^src_prepare() {" "$ebuild_file"; then
                    echo "Adding line to src_prepare in $ebuild_file"
                    sed -i "/^src_prepare() {/ { N; s|\\n|\\n\\tfilter-flags -Wl,-z,defs\\n| }" "$ebuild_file"
                fi
                if grep -q "^src_unpack() {" "$ebuild_file"; then
                    echo "Adding line to src_unpack in $ebuild_file"
                    sed -i "/^src_unpack() {/ { N; s|\\n|\\n\\tfilter-flags -Wl,-z,defs\\n| }" "$ebuild_file"
                fi
                if grep -q "^python_configure_all() {" "$ebuild_file"; then
                    echo "Adding line to python_configure_all in $ebuild_file"
                    sed -i "/^python_configure_all() {/ { N; s|\\n|\\n\\tfilter-flags -Wl,-z,defs\\n| }" "$ebuild_file"
                fi
            done
		' sh {} +
		echo "Updated for ${package}."
	else
		echo "Directory for ${package} not found."
	fi
done

echo "Starting to process each package to keep only the latest ebuild..."

for package in "${PACKAGES[@]}"; do
	package_dir="${PACKAGE_DIR}/${package}"
	if [ -d "${package_dir}" ]; then
		echo "Processing ${package} in ${package_dir}..."

		find "${package_dir}" -type f -name "*.ebuild" | sort -V | head -n -1 | while read ebuild; do
			echo "Deleting old ebuild: ${ebuild}"
			rm "${ebuild}"
		done

		echo "Cleanup of old ebuilds complete for ${package}."
	else
		echo "Directory ${package_dir} not found."
	fi
done

echo "All packages processed, and old ebuilds removed."

echo "Starting to update KEYWORDS in ebuild files..."

for package in "${PACKAGES[@]}"; do
	package_dir="${PACKAGE_DIR}/${package}"
	if [ -d "${package_dir}" ]; then
		echo "Processing ${package} in ${package_dir}..."
		echo "Updating KEYWORDS for ${package} in ${package_dir}..."
		find "${package_dir}" -type f -name "*.ebuild" -exec sed -i'' '/^KEYWORDS=/ s/^KEYWORDS=".*"/KEYWORDS="amd64 arm64"/g' {} +
		echo "KEYWORDS updated for ${package}."
	fi
done

declare -A replacements=(
	["app-misc/ca-certificates"]="app-var/ca-certificates"
	["dev-libs/libffi"]="lib-core/libffi"
	["dev-libs/libxml2"]="lib-core/libxml2"
	["dev-libs/libxslt"]="lib-core/libxslt"
	["dev-libs/libyaml"]="lib-dev/libyaml"
	["dev-libs/tree-sitter"]="lib-dev/tree-sitter"
	["dev-libs/openssl"]="lib-net/openssl"
	["sys-libs/timezone-data"]="lib-core/tzdb"
)

for package in "${PACKAGES[@]}"; do
	package_dir="${PACKAGE_DIR}/${package}"
	if [ -d "${package_dir}" ]; then
		for old_text in "${!replacements[@]}"; do
			new_text="${replacements[$old_text]}"
			echo "Replacing '${old_text}' with '${new_text}' in ${package_dir}..."
			find "${package_dir}" -type f -name "*.ebuild" -exec sed -i'' "s|${old_text}|${new_text}|g" {} +
		done
		echo "Text replacements completed for ${package}."
	fi
done

remove_strings=('bash-completion-r1' 'optfeature' 'virtualx')

for package in "${PACKAGES[@]}"; do
	package_dir="${PACKAGE_DIR}/${package}"
	if [ -d "${package_dir}" ]; then
		echo "Processing ${package} in ${package_dir} for string removals..."
		find "${package_dir}" -type f -name "*.ebuild" -print0 | while IFS= read -r -d '' ebuild_file; do
			echo "Updating ${ebuild_file}..."
			for remove_string in "${remove_strings[@]}"; do
				sed -i'' -e "s/[[:space:]]*${remove_string}[[:space:]]*/ /g" \
					-e '/^inherit[[:space:]]*$/d' "${ebuild_file}"
			done
		done
		echo "String removals completed for ${package}."
	fi
done

echo "Cleanup complete. Script execution finished."

generate_manifest() {
	local package=$1
	local package_path="${PACKAGE_DIR}/${package}"

	if [ -d "${package_path}" ]; then
		ebuild "${package_path}"/*.ebuild manifest
	fi
}

commit_changes() {
	local package=$1
	local package_path="${PACKAGE_DIR}/${package}"

	echo "Committing changes for package: ${package}"

	local ebuild_file=$(find "${package_path}" -type f -name "${package}*.ebuild" | head -n 1)
	if [[ -z "$ebuild_file" ]]; then
		echo "Ebuild file not found for ${package}"
		return 1
	fi

	local filename=$(basename "$ebuild_file")
	local version=$(echo $filename | sed -r "s/^${package}-([0-9]+(\.[0-9]+)*(_p[0-9]+)?(-r[0-9]+)?)\.ebuild$/\1/")

	if [[ -z "$version" || "$version" == "$filename" ]]; then
		echo "Version extraction failed for ${package}"
		return 1
	fi

	echo "Version found: ${version}"

	finalize_update "${package_path}" "${package}" "${filename}" "${version}"
}

main() {
	echo "Starting script execution..."

	for package in "${PACKAGES[@]}"; do
		echo "Processing package: ${package}"
		generate_manifest "${package}" || { echo "Failed to generate manifest for ${package}"; return 1; }
		commit_changes "${package}" || { echo "Failed to commit changes for ${package}"; continue; }
	done


	rm -rf "${GENTOO_PATH}"
	echo "Script execution finished."
}

main "$@"
