# lockstep-managed: cargo-crate
EAPI=8
MERGE_MANIFEST_MODE="tree-blake3-v1"

CRATE_NAME="regex-automata"
CRATE_VERSION="0.4.18"
CRATE_CHECKSUM="ad8553b9b26413251cbf30e620595c7a41b3887f03da04579c0e6b0d6a06b4b2"
CRATE_SOURCE="registry+https://github.com/rust-lang/crates.io-index"
CRATE_SOURCE_KIND="registry"

inherit cargo-crate

DESCRIPTION="Automata construction and matching using regular expressions."
HOMEPAGE="https://github.com/rust-lang/regex/tree/master/regex-automata"
LICENSE="|| ( MIT Apache-2.0 )"
SLOT="${PV}"
KEYWORDS="amd64 arm64"

CARGO_CRATE_FEATURES=(
	"alloc"
	"default"
	"dfa"
	"dfa-build"
	"dfa-onepass"
	"dfa-search"
	"hybrid"
	"internal-instrument"
	"internal-instrument-pikevm"
	"logging"
	"meta"
	"nfa"
	"nfa-backtrack"
	"nfa-pikevm"
	"nfa-thompson"
	"perf"
	"perf-inline"
	"perf-literal"
	"perf-literal-multisubstring"
	"perf-literal-substring"
	"std"
	"syntax"
	"unicode"
	"unicode-age"
	"unicode-bool"
	"unicode-case"
	"unicode-gencat"
	"unicode-perl"
	"unicode-script"
	"unicode-segment"
	"unicode-word-boundary"
)
