# lockstep-managed: cargo-crate
EAPI=8
MERGE_MANIFEST_MODE="tree-blake3-v1"

CRATE_NAME="objc2-quartz-core"
CRATE_VERSION="0.3.2"
CRATE_CHECKSUM="96c1358452b371bf9f104e21ec536d37a650eb10f7ee379fff67d2e08d537f1f"
CRATE_SOURCE="registry+https://github.com/rust-lang/crates.io-index"
CRATE_SOURCE_KIND="registry"

inherit cargo-crate

DESCRIPTION="Bindings to the QuartzCore/CoreAnimation framework"
HOMEPAGE="https://github.com/madsmtm/objc2"
LICENSE="|| ( Zlib Apache-2.0 MIT )"
SLOT="${PV}"
KEYWORDS="amd64 arm64"

CARGO_CRATE_FEATURES=(
	"CAAnimation"
	"CABase"
	"CAConstraintLayoutManager"
	"CADisplayLink"
	"CAEAGLLayer"
	"CAEDRMetadata"
	"CAEmitterCell"
	"CAEmitterLayer"
	"CAFrameRateRange"
	"CAGradientLayer"
	"CALayer"
	"CAMediaTiming"
	"CAMediaTimingFunction"
	"CAMetalDisplayLink"
	"CAMetalLayer"
	"CAOpenGLLayer"
	"CARemoteLayerClient"
	"CARemoteLayerServer"
	"CARenderer"
	"CAReplicatorLayer"
	"CAScrollLayer"
	"CAShapeLayer"
	"CATextLayer"
	"CATiledLayer"
	"CATransaction"
	"CATransform3D"
	"CATransformLayer"
	"CAValueFunction"
	"CoreAnimation"
	"alloc"
	"bitflags"
	"block2"
	"default"
	"gnustep-1-7"
	"gnustep-1-8"
	"gnustep-1-9"
	"gnustep-2-0"
	"gnustep-2-1"
	"libc"
	"objc2-core-foundation"
	"objc2-core-graphics"
	"objc2-core-video"
	"objc2-metal"
	"objc2-open-gl"
	"std"
	"unstable-darwin-objc"
)
