# lockstep-managed: cargo-crate
EAPI=8
MERGE_MANIFEST_MODE="tree-blake3-v1"

CRATE_NAME="rust_decimal"
CRATE_VERSION="1.43.0"
CRATE_CHECKSUM="7653272e75dcac41dc199fbea6f5797633994fafd339943c06c9af16bf29cd3a"
CRATE_SOURCE="registry+https://github.com/rust-lang/crates.io-index"
CRATE_SOURCE_KIND="registry"

inherit cargo-crate

DESCRIPTION="Decimal number implementation written in pure Rust suitable for financial and fixed-precision calculations."
HOMEPAGE="https://github.com/paupino/rust-decimal"
LICENSE="MIT"
SLOT="${PV}"
KEYWORDS="amd64 arm64"

CARGO_CRATE_FEATURES=(
	"align16"
	"borsh"
	"bytemuck"
	"c-repr"
	"db-diesel-mysql"
	"db-diesel-postgres"
	"db-diesel2-mysql"
	"db-diesel2-postgres"
	"db-postgres"
	"db-tokio-postgres"
	"default"
	"legacy-ops"
	"macros"
	"maths"
	"maths-nopanic"
	"ndarray"
	"proptest"
	"rand"
	"rand-0_9"
	"rocket-traits"
	"rust-fuzz"
	"serde"
	"serde-arbitrary-precision"
	"serde-bincode"
	"serde-float"
	"serde-str"
	"serde-with-arbitrary-precision"
	"serde-with-float"
	"serde-with-str"
	"std"
	"tokio-pg"
	"wasm"
)
